### ISSUE TITLE
Where to start

### ISSUE THREAD

**Issue by robots** [kuba2k2/datastruct#5]
If you want to start using this project, there is very little documentation to this powerful tool.

Here are few projects where to look for "usages":

https://github.com/tuya-cloudcutter/cloudcutter-universal/blob/master/cloudcutter/modules/dhcp/structs.py
https://github.com/tuya-cloudcutter/bk7231tools/blob/main/bk7231tools/analysis/kvstorage.py
https://github.com/libretiny-eu/ltchiptool/blob/master/uf2tool/models/partition.py

**Comment by kuba2k2** [comment]
Thanks, I added these to the README.
